# Generated by Django 5.2 on 2025-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_remove_tag_news_news_tags_comment_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="Комментарий"),
        ),
    ]
