# Generated by Django 5.2 on 2025-04-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
    ]
